var localizedStrings = {
    'Done': 'Fertig',
    'Treat first row as day': 'Erste Zeile als Tag behandeln',
    'Treat first column as period': 'Erste Spalte als Zeit behandeln',
    'Ignore': 'Ignorieren',
    'Display next day': 'Zum nächsten Tag wechseln',
    "at %d o'clock": 'um %d Uhr',
    'Use <a href="http://www.tilltheis.de/projects/timetable-widget/#isoWeeks">ISO weeks</a>': 'Wochen nach <a href="http://www.tilltheis.de/projects/timetable-widget/#isoWeeks">ISO-Standard</a>',
    'Monday': 'Montag',
    'Tuesday': 'Dienstag',
    'Wednesday': 'Mittwoch',
    'Thursday': 'Donnerstag',
    'Friday': 'Freitag',
    '%y-%m-%d': '%d.%m.%y',
    'http://www.tilltheis.de/projects/timetable-widget': 'http://www.tilltheis.de/projects/timetable-widget',
    'Import Options': 'Import Einstellungen',
    'Odd week': 'Ungerade Woche',
    'Even week': 'Gerade Woche',
    'Save': 'Speichern',
    'Cancel': 'Abbrechen',
    'Edit Timetable For Even Weeks': 'Stundenplan für gerade Wochen bearbeiten',
    'Edit Timetable For Odd Weeks': 'Stundenplan für ungerade Wochen bearbeiten',
    'Time': 'Zeit'
};
