var localizedStrings = {
    'Done': 'Done',
    'Treat first row as day': 'Treat first row as day',
    'Treat first column as period': 'Treat first column as time',
    'Ignore': 'Ignore',
    'Display next day': 'Display next day',
    "at %d o'clock": "at %d hours",
    'at 1 hours': 'at 1 hour',
    'Use <a href="http://www.tilltheis.de/projects/timetable-widget/#isoWeeks">ISO weeks</a>': 'Use <a href="http://www.tilltheis.de/projects/timetable-widget/#isoWeeks">ISO weeks</a>',
    'Monday': 'Monday',
    'Tuesday': 'Tuesday',
    'Wednesday': 'Wednesday',
    'Thursday': 'Thursday',
    'Friday': 'Friday',
    '%y-%m-%d': '%y-%m-%d',
    'http://www.tilltheis.de/projects/timetable-widget': 'http://www.tilltheis.de/projects/timetable-widget',
    'Import Options': 'Import Options',
    'Odd week': 'Odd week',
    'Even week': 'Even week'
};
